apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: u7bcrj4g9-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/u7bcrj4g9-java-springboot-gitops